steps:
  build:
    image: python:3.10-slim-bullseye
    commands:
      - apt update && apt install curl -y
      - chmod +x scripts/get-pants.sh
      - scripts/get-pants.sh --bin-dir pants
      - "./pants fmt ::"