steps:
  check:
    group: validations
    pull: true
    image: mikaelsouza/pants:latest
    commands:
      - "pants check ::"
    when:
      - event: push

  lint:
    group: validations
    pull: true
    image: mikaelsouza/pants:latest
    commands:
      - "pants lint ::"
    when:
      - event: push

  test:
    group: validations
    pull: true
    image: mikaelsouza/pants:latest
    commands:
      - "pants test ::"
    when:
      - event: push
