[GLOBAL]
pants_version = "2.17.0"
pants_workdir = ".pants/.pants.d"
pants_subprocessdir = ".pants/.pids"
pants_distdir = ".monorepo/"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.build_files.fmt.black",
]

[python]
interpreter_constraints = ["==3.10.*"]
pip_version = "latest"
enable_resolves = true
default_resolve = "monorepo"

[python.resolves]
monorepo = "lockfiles/monorepo.lock"

[python-infer]
use_rust_parser = true

[anonymous-telemetry]
enabled = false

[black]
interpreter_constraints = ["==3.10.*"]

[docformatter]
interpreter_constraints = ["==3.10.*"]

[mypy]
interpreter_constraints = ["==3.10.*"]
args = ["--ignore-missing-imports"]