[GLOBAL]
pants_version = "2.18.1"
pants_workdir = ".pants/.pants.d"
pants_subprocessdir = ".pants/.pids"
pants_distdir = ".monorepo/"
concurrent = true
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.build_files.fmt.black",
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck",
]

[python]
interpreter_constraints = ["==3.10.*"]
pip_version = "latest"
enable_resolves = true
default_resolve = "monorepo"

[python.resolves]
monorepo = "deps/lockfiles/monorepo.lock"

[python-infer]
use_rust_parser = true

[anonymous-telemetry]
enabled = false

[mypy]
args = ["--ignore-missing-imports", "--cache-dir", ".monorepo/.mypy_cache"]

[pytest]
install_from_resolve = "monorepo"
