__defaults__(all=dict(resolve="web"))

python_sources(
    name="py-sources",
    sources=["**/*.py"],
)

python_tests(
    name="py-tests",
    sources=[
        "**/test_*.py",
    ],
)

shell_sources(
    name="scripts",
    sources=[
        "**/*.sh",
    ],
)
